### ISSUE TITLE
Missing Pset6

### ISSUE THREAD

**Issue by christabella** [mlhcmit/psets#1]
Hello, thanks a lot for posting the course materials! I noticed that the link to Pset 6 was missing (https://mlhc19mit.github.io) and was wondering if Pset 6 could be posted here as well? Thank you!

**Comment by wboag** [comment]
https://github.com/mlhc19mit/psets/blob/master/ps6-mlhc-spring2019.pdf

**Comment by christabella** [comment]
Ahh oops, thank you!
